# Generated by Django 4.2.10 on 2024-03-14 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_subscriber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('body', models.TextField(max_length=500)),
                ('attachment', models.FileField(blank=True, upload_to='email_attachments/')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
